### ISSUE TITLE
Examples of use on other projects

### ISSUE THREAD

**Issue by ronschaeffer** [leech001/hass-mqtt-discovery#7]
Thanks very much for this.

Can you point me to any examples of other projects using this library?

**Comment by fgervais** [comment]
Here’s one of my projects: https://github.com/fgervais/project-smart-fridge/blob/043bafc83f9bad86ea2f18b37e432731a74de9db/firmware/main.py#L126

**Comment by ronschaeffer** [comment]
@fgervais Great, thanks. Looks like a critical project, too!
